backend:
  name: git-gateway
  branch: main # Ou o nome da sua branch principal

media_folder: "public/img" # Pasta onde as imagens serão armazenadas no seu repositório
public_folder: "/img" # Caminho público para acessar as imagens

collections:
  - name: "noticias" # Nome da sua coleção de notícias
    label: "Notícias" # Label que aparecerá na interface do CMS
    folder: "_posts" # Pasta onde os arquivos de notícias serão armazenados (crie esta pasta se não existir)
    create: true # Permite criar novos arquivos
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Formato do nome do arquivo

    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string", default: "Seu Nome" }
      - { label: "Imagem de Capa", name: "image", widget: "image" }
      - { label: "Corpo", name: "body", widget: "markdown" }
      # Adicione aqui outros campos que suas notícias possam ter
      # Exemplo:
      # - { label: "Categoria", name: "categoria", widget: "string" }
      # - { label: "Tags", name: "tags", widget: "list" }
