backend:
  name: github
  repo: silvoasantosc/porto-calvo-noticias # Ajuste para seu nome de usuário/repositório
  branch: main # Mantenha como está se sua branch principal for 'main'
  base_url: https://api.netlify.com # Necessário para autenticação OAuth

# Mantenha as configurações de pasta de mídia como estão
media_folder: "public/img" # Pasta onde as imagens serão armazenadas no seu repositório
public_folder: "/img" # Caminho público para acessar as imagens

# Adicione o modo editorial para melhor fluxo de trabalho
publish_mode: editorial_workflow

collections:
  - name: "noticias" # Mantenha como está
    label: "Notícias" # Mantenha como está
    folder: "_posts" # Mantenha como está, mas certifique-se de que esta pasta existe
    create: true # Mantenha como está
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Mantenha como está
    fields: # Mantenha os campos como estão
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string", default: "Seu Nome" }
      - { label: "Imagem de Capa", name: "image", widget: "image" }
      - { label: "Corpo", name: "body", widget: "markdown" }
      # Adicione mais campos conforme necessário
      - { label: "Categoria", name: "categoria", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list" }
      
  # Adicione mais coleções se necessário, como páginas estáticas
  - name: "paginas"
    label: "Páginas"
    folder: "pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Corpo", name: "body", widget: "markdown" }
      - { label: "Ordem no Menu", name: "ordem", widget: "number", default: 1 }

